name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # ... your build and test steps ...

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions: # Add this section
      contents: write # Grant write permissions to the contents of the repository
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Or your build output directory
