name: Deploy App with Observability

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Deploy Services
      run: |
        docker-compose -f docker-compose.yml up -d --build

    - name: Wait for Jaeger and Grafana
      run: |
        sleep 15
        curl -f http://localhost:16686 || echo "Jaeger not ready"
        curl -f http://localhost:3000 || echo "Grafana not ready"
