name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    name: Blue-Green Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine current active environment
        id: env
        run: |
          ACTIVE=$(cat active-env.txt)
          if [ "$ACTIVE" = "blue" ]; then
            echo "env_to_use=green" >> $GITHUB_OUTPUT
          else
            echo "env_to_use=blue" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to ${{ steps.env.outputs.env_to_use }}
        run: |
          echo "Deploying to ${{ steps.env.outputs.env_to_use }} environment..."
          # Add your actual deployment commands here
          echo "Finished deployment."

      - name: Run Smoke Tests
        run: |
          echo "Testing ${{ steps.env.outputs.env_to_use }} environment..."
          # Add real smoke test commands here
          echo "Smoke tests passed."

      - name: Switch traffic to ${{ steps.env.outputs.env_to_use }}
        run: |
          echo "${{ steps.env.outputs.env_to_use }}" > active-env.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add active-env.txt
          git commit -m "Switched traffic to ${{ steps.env.outputs.env_to_use }}"
          git push
