name: SLA Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Can run manually too

jobs:
  check-sla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const now = new Date();

            for (const issue of issues) {
              const labels = issue.labels.map(l => l.name);
              const created = new Date(issue.created_at);
              let due = null;

              if (labels.includes("sla-48h")) {
                due = new Date(created.getTime() + 48 * 60 * 60 * 1000);
              } else if (labels.includes("sla-5d")) {
                due = new Date(created.getTime() + 5 * 24 * 60 * 60 * 1000);
              } else if (labels.includes("sla-7d")) {
                due = new Date(created.getTime() + 7 * 24 * 60 * 60 * 1000);
              }

              if (due && now > due && !labels.includes("sla-overdue")) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ["sla-overdue"]
                });
              }
            }
